### ISSUE TITLE
bug: FileRequestHandler error:  Too many open files

### ISSUE THREAD

**Issue by chen56** [ReactiveX/RxNetty#316]
rxnetty-0.4.4

at FileRequestHandler.java:95: Too many open files.
RandomAccessFile not closed.

Steps to reproduce the bug:  
1.

> netstat -anp|grep 25001
> 20576

2.

> ls -l /proc/20576/fd/ | wc -l
> 0

3.
access the static file uri 

4.

> ls -l /proc/20576/fd/ | wc -l
> 15

error:
java.io.FileNotFoundException: /home/c/resources/static/user/index.html (Too many open files)\n\t
at java.io.RandomAccessFile.open(Native Method)\n\tat java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)\n\t
at io.reactivex.netty.protocol.http.server.file.FileRequestHandler.handle(FileRequestHandler.java:95)\n\t
at io.reactivex.netty.protocol.http.server.RequestHandlerWithErrorMapper.handle(RequestHandlerWithErrorMapper.java:46)\n\t
at firebats.http.server.old.AbstractRoute$1.handle(AbstractRoute.java:67)\n\t
at firebats.http.server.old.AbstractRoute$1.handle(AbstractRoute.java:61)\n\t
at firebats.http.server.old.AbstractRoute$2.call(AbstractRoute.java:115)\n\t

**Comment by NiteshKant** [comment]
Thanks @chen56 for reporting the issue, will look at it.
