### ISSUE TITLE
When using RxNetty as a proxy content is lost under moderate load

### ISSUE THREAD

**Issue by s-urbaniak** [ReactiveX/RxNetty#336]
Hi,

First thanks a lot for the great project! We are evaluating RxNetty for using in production but are experiencing lost content during fan-in under moderate load in conjunction with connection pooling.

This issue does not happen when I disable connection pooling.

Our use case is pretty simple: One incoming request causes a few fan-out requests which are then combined to a response. More concretely this is a typical web application accepting http requests, calling external services and rendering an HTML response.

I was able to strip down the problem to a single main method. The canonical fan-out fan-in procedure is implemented as follows:

``` java
    private static final Joiner joiner = Joiner.on("");

    public static void main(String[] args) {
        RxNetty.useMetricListenersFactory(new MetricsFactory());
        ClientFactory factory = new ClientFactory();
        URI uri = MoreUris.fromString("http://service-url");
        HttpClient<ByteBuf, ByteBuf> client = factory.newClient(uri);

        Gson gson = new Gson();
        RequestHandler<ByteBuf, ByteBuf> requestHandler = (serverReq, serverRes) -> {
            HttpClientRequest<ByteBuf> clientReq = HttpClientRequest.createGet("/path");

            return client.submit(clientReq)
                .flatMap(res -> {
                    if (res.getStatus().code() != HttpResponseStatus.OK.code()) {
                        return Observable.error(new NetworkException(res.getStatus().code(), clientReq.getUri()));
                    }

                    return res
                        .getContent()
                        .map(chunk -> chunk.toString(Charsets.UTF_8))
                        .toList()
                        .map(l -> {
                            Preconditions.checkArgument(l.size() > 0, "content list must not be empty");
                            String body = joiner.join(l);
                            JsonObject json = gson.fromJson(body, JsonObject.class);
                            return json;
                        });
                })
                .single()
                .flatMap(json -> {
                    Preconditions.checkNotNull(json);
                    serverRes.writeString(json.toString());
                    return serverRes.close();
                });
        };

        HttpServer<ByteBuf, ByteBuf> server = RxNetty.createHttpServer(8181, requestHandler);
        server.startAndWait();
    }
```

In order to trace down the issue I implemented a custom MetricEventsListenerFactory (logging ClientMetrics and ServerMetrics), a logging ChannelDuplexHandler and a seperate client SharedNioEventLoopGroup having a different threadNamePrefix for a better tracing of server ("rxnetty-nio-eventloop") event loop threads and client ("rxclient-nio-eventloop") event loop threads.

These measures resemble the following log trace:

A request comes in:

```
[rxnetty-nio-eventloop-3-3] HttpLoggingHandler  <-- [id: 0xb88591ae, /127.0.0.1:61839 => /127.0.0.1:8181] GET /webapp
[rxnetty-nio-eventloop-3-3] ServerMetricsEvent event=RequestHeadersReceived duration=-1 null throwable=null value=null
[rxnetty-nio-eventloop-3-3] ServerMetricsEvent event=NewRequestReceived duration=-1 null throwable=null value=null
[rxnetty-nio-eventloop-3-3] ServerMetricsEvent event=RequestHandlingStart duration=0 MILLISECONDS throwable=null value=null
```

The client decides to reuse a connection from the pool

```
[rxnetty-nio-eventloop-3-3] ClientMetricsEvent event=RequestSubmitted duration=-1 null throwable=null value=null
[rxnetty-nio-eventloop-3-3] ClientMetricsEvent event=PoolAcquireStart duration=-1 null throwable=null value=null
[rxnetty-nio-eventloop-3-3] ClientMetricsEvent event=PooledConnectionReuse duration=0 MILLISECONDS throwable=null value=null
[rxnetty-nio-eventloop-3-3] ClientMetricsEvent event=PoolAcquireSuccess duration=0 MILLISECONDS throwable=null value=null
```

The connection is immediately released (why?), delivering an empty content observable and causing the single() operator to throw an exception:

```
[rxnetty-nio-eventloop-3-3] ServerMetricsEvent event=RequestContentReceived duration=-1 null throwable=null value=null
[rxnetty-nio-eventloop-3-3] ServerMetricsEvent event=RequestReceiveComplete duration=0 MILLISECONDS throwable=null value=null
[rxclient-nio-eventloop-5-4] UserEventCatcher  userEventTriggered evt=io.reactivex.netty.client.PooledConnectionReleasedEvent@3e24c248
connection=io.reactivex.netty.client.PooledConnection@28ac0c0d
[rxclient-nio-eventloop-5-4] ClientMetricsEvent event=PoolReleaseStart duration=-1 null throwable=null value=null
[rxclient-nio-eventloop-5-4] ClientMetricsEvent event=PoolReleaseSuccess duration=0 MILLISECONDS throwable=null value=null
[rxclient-nio-eventloop-5-4] ERROR ErrorTracer channel=[id: 0xbb140222, /127.0.0.1:61849 => /127.0.0.1:8181]
java.util.NoSuchElementException: Sequence contains no elements
        at rx.internal.operators.OperatorSingle$1.onCompleted(OperatorSingle.java:82)
[rxclient-nio-eventloop-5-4] INFO  i.r.n.s.ServerMetricsEvent event=RequestHandlingFailed duration=1 MILLISECONDS throwable=java.util.No
SuchElementException: Sequence contains no elements value=null
[rxclient-nio-eventloop-5-4] ServerMetricsEvent event=FlushStart duration=-1 null throwable=null value=null
[rxclient-nio-eventloop-5-4] ClientMetricsEvent  event=RequestProcessingComplete duration=4 MILLISECONDS throwable=null value=null
[rxnetty-nio-eventloop-3-3] ServerMetricsEvent event=ResponseHeadersWriteStart duration=-1 null throwable=null value=null
[rxnetty-nio-eventloop-3-3] HttpLoggingHandler  --> [id: 0xbb140222, /127.0.0.1:61849 => /127.0.0.1:8181] 500 Internal Server Error
```

The intended request is nevertheless later tried but cancelled:

```
[rxclient-nio-eventloop-5-4] ServerMetricsEvent event=FlushStart duration=-1 null throwable=null value=null
[rxclient-nio-eventloop-5-4] UserEventCatcher  userEventTriggered evt=io.reactivex.netty.client.ConnectionReuseEvent@7f375546 connection=io.reactivex.netty.client.PooledConnection@28ac0c0d
[rxclient-nio-eventloop-5-4] ClientMetricsEvent  event=RequestHeadersWriteStart duration=-1 null throwable=null value=null
[rxclient-nio-eventloop-5-4] HttpLoggingHandler  --> [id: 0x2a96bf56, /10.250.213.40:61783 => m.mobile.de/91.211.75.174:80] GET /internal-service HTTP/1.1
[rxclient-nio-eventloop-5-4] ClientMetricsEvent  event=WriteStart duration=-1 null throwable=null value=106
[rxclient-nio-eventloop-5-4] ClientMetricsEvent  event=RequestContentWriteStart duration=-1 null throwable=null value=null
[rxclient-nio-eventloop-5-4] ClientMetricsEvent  event=WriteStart duration=-1 null throwable=null value=0
[rxclient-nio-eventloop-5-4] ClientMetricsEvent  event=FlushStart duration=-1 null throwable=null value=null
[rxclient-nio-eventloop-5-4] ClientMetricsEvent  event=WriteSuccess duration=0 MILLISECONDS throwable=null value=106
[rxclient-nio-eventloop-5-4] ClientMetricsEvent  event=RequestHeadersWriteSuccess duration=0 MILLISECONDS throwable=null value=null
[rxclient-nio-eventloop-5-4] ClientMetricsEvent  event=WriteSuccess duration=0 MILLISECONDS throwable=null value=0
[rxclient-nio-eventloop-5-4] ClientMetricsEvent  event=RequestContentWriteSuccess duration=0 MILLISECONDS throwable=null value=null
[rxclient-nio-eventloop-5-4] ClientMetricsEvent  event=FlushFailed duration=0 MILLISECONDS throwable=java.util.concurrent.CancellationException value=null
[rxclient-nio-eventloop-5-4] ClientMetricsEvent  event=RequestWriteFailed duration=5 MILLISECONDS throwable=java.util.concurrent.CancellationException value=null
```

I am willing to share the sample project in case further investigation is needed. But maybe you already see a faulty usage of the Rx API in my code?

Thanks a lot in advance!
Sergiusz

**Comment by s-urbaniak** [comment]
Hello,

I have some more tracing. It seems that the request in-flight gets a PoolRelease event due to the completion of a previous client response in the very same client eventloop thread.

The first PoolRelease event is (correctly) caused by the completion of the previous ResponseState and is also causing (wrongly) the unsubscription of the following request.

```
[rxclient-nio-eventloop-5-4] UserEventCatcher  userEventTriggered evt=io.reactivex.netty.client.PooledConnectionReleasedEvent@3bccbad5 
connection=io.reactivex.netty.client.PooledConnection@50466492
[rxclient-nio-eventloop-5-4] ClientMetricsEvent  event=PoolReleaseStart duration=-1 null throwable=null value=null
[rxclient-nio-eventloop-5-4] ClientMetricsEvent  event=PoolReleaseSuccess duration=0 MILLISECONDS throwable=null value=null
...
[rxclient-nio-eventloop-5-4] UserEventCatcher  userEventTriggered evt=io.reactivex.netty.client.PooledConnectionReleasedEvent@1fc8c1e6 
connection=io.reactivex.netty.client.PooledConnection@50466492
[rxclient-nio-eventloop-5-4] ClientMetricsEvent  event=PoolReleaseStart duration=-1 null throwable=null value=null
[rxclient-nio-eventloop-5-4] ClientMetricsEvent  event=PoolReleaseSuccess duration=0 MILLISECONDS throwable=null value=null
[rxclient-nio-eventloop-5-4] ErrorTracer  unexpected error, channel=[id: 0xbb140222, /127.0.0.1:61849 => /127.0.0.1:8181]
java.util.NoSuchElementException: Sequence contains no elements
        at rx.internal.operators.OperatorSingle$1.onCompleted(OperatorSingle.java:82)
```

I recognized that the response should be exchanged in ClientRequestResponseConverter#userEventTriggered but the above trace indicates that this did not happen.

On the other hand the server event loop did receive a PooledConnectionReuse event during connection acquire but this happened in the server thread. Is guess there is a race/visibility issue between the server and client event loop thread here during connection reuse?! This would also explain why the request is tried anyways (but cancelled).

Thanks,
Sergiusz

**Comment by s-urbaniak** [comment]
Hello,

I guess I discovered the bug which was fixed in 6d13b3f0de25832760855a30411f604ef25e5c02 ;-)

Sorry, I just realized the fix while wandering through ClientRequestResponseConverter's source code.

We will retest with version 0.4.6.

**Comment by NiteshKant** [comment]
@s-urbaniak apologies for the late reply on this.

Yep, your symptoms did sound like the fix I made in that commit. Lemme know if you find the same issue with 0.4.6

**Comment by s-urbaniak** [comment]
Hi,

No problem, we reran our tests and did not experience any more races.

Thanks!
Sergiusz
