### ISSUE TITLE
IllegalReferenceCountException when using RxNetty 0.4.8 with HttpContentDecompressor

### ISSUE THREAD

**Issue by thaggie** [ReactiveX/RxNetty#345]
I'm using the HttpContentDecompressor to be able to work with compressed data, I use a pipeline configurator (as below) and then set `request.withHeader("Accept-Encoding", "gzip, deflate");` when making a request.

This is working in **0.4.6** but when I try to upgrade to **0.4.8** I get an IllegalReferenceCountException (full stack below).

I can't really see what I'm doing wrong (if anything) - is this a regression?

```
private static final PipelineConfigurator<HttpClientResponse<ByteBuf>, HttpClientRequest<ByteBuf>> gzipPipelineConfigurator = new PipelineConfigurator<HttpClientResponse<ByteBuf>, HttpClientRequest<ByteBuf>>() {
    @Override
    public void configureNewPipeline(ChannelPipeline pipeline) {
        ChannelHandler handlers = new HttpContentDecompressor();
        pipeline.addLast(handlers);         
    }
};

...

HttpClientBuilder<ByteBuf, ByteBuf> builder = RxNetty.<ByteBuf, ByteBuf> newHttpClientBuilder(host, port);

    builder.appendPipelineConfigurator(gzipPipelineConfigurator);

```

```
io.netty.util.IllegalReferenceCountException: refCnt: 0
    at io.netty.buffer.DefaultByteBufHolder.content(DefaultByteBufHolder.java:39) ~[netty-buffer-4.0.25.Final.jar:4.0.25.Final]
    at io.reactivex.netty.protocol.http.client.ClientRequestResponseConverter.channelRead(ClientRequestResponseConverter.java:137) ~[rxnetty-0.4.8.jar:0.4.8]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182) [netty-codec-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:147) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:283) [netty-handler-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1038) [netty-handler-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:911) [netty-handler-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:268) [netty-codec-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:168) [netty-codec-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.reactivex.netty.metrics.BytesInspector.channelRead(BytesInspector.java:59) [rxnetty-0.4.8.jar:0.4.8]
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-common-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-common-4.0.25.Final.jar:4.0.25.Final]
    at java.lang.Thread.run(Thread.java:744) [na:1.8.0]
```

**Comment by NiteshKant** [comment]
@thaggie apologies for the delayed response.

> I can't really see what I'm doing wrong (if anything) - is this a regression?

Could be, I do not particularly use the decompressor in any usecase so am not sure if this is a regression or not. 
Can you provide a complete reproducer (client & server) so that I can reproduce this locally?

**Comment by ghost** [comment]
In the form of a PR with a unit test?

**Comment by NiteshKant** [comment]
@thaggie PR would be great!

**Comment by thaggie** [comment]
I've tried this against the 0.4.6 tag and it passes.

**Comment by brharrington** [comment]
We use the gzip decompressor and haven't seen this issue. It looks like the main difference is instead of appending we create a composite and explicitly set the configurator:

``` java
  HttpClientBuilder<ByteBuf, ByteBuf> builder = RxNetty.<ByteBuf, ByteBuf> newHttpClientBuilder(host, port);
  builder.pipelineConfigurator(new PipelineConfiguratorComposite<HttpClientResponse<ByteBuf>, HttpClientRequest<ByteBuf>>(
    new HttpClientPipelineConfigurator<ByteBuf, ByteBuf>(),
    gzipPipelineConfigurator));
  HttpClient<ByteBuf, ByteBuf> client = builder.build();
```

It does seem like append should work though.

**Comment by thaggie** [comment]
That works for me.

**Comment by NiteshKant** [comment]
Great! thanks @brharrington!

**Comment by Crystark** [comment]
Just pointing out that the other difference is that @brharrington doesn't use the `HttpObjectAggregationConfigurator` whereas @thaggie does because `appendPipelineConfigurator` just adds the `gzipPipelineConfigurator` to the default ones which are `HttpClientPipelineConfigurator` and `HttpObjectAggregationConfigurator`
