### ISSUE TITLE
SSL causes exception to be thrown on every request in VoidChannelPromise

### ISSUE THREAD

**Issue by ashley-taylor** [ReactiveX/RxNetty#348]
Sample code to recreate exception

``` java
    public static void main(String[] args)  {
        RxNetty.newHttpServerBuilder(1234, (request , response) -> {
            return response.close();
        }).withSslEngineFactory(DefaultFactories.selfSigned()).build().startAndWait();
    }
```

```
java.lang.IllegalStateException: void future
    at io.netty.channel.VoidChannelPromise.fail(VoidChannelPromise.java:178) ~[netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.VoidChannelPromise.addListener(VoidChannelPromise.java:44) ~[netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.VoidChannelPromise.addListener(VoidChannelPromise.java:24) ~[netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.reactivex.netty.metrics.BytesInspector.publishBytesWritten(BytesInspector.java:84) ~[rxnetty-0.4.8.jar:0.4.8]
    at io.reactivex.netty.metrics.BytesInspector.write(BytesInspector.java:67) ~[rxnetty-0.4.8.jar:0.4.8]
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626) [netty-transport-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.handler.ssl.SslHandler.finishWrap(SslHandler.java:533) [netty-handler-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:504) [netty-handler-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:454) [netty-handler-4.0.25.Final.jar:4.0.25.Final]
```

Cheers,
Ashley

**Comment by NiteshKant** [comment]
@ashley-taylor Thanks for reporting the bug.

The complete error log is:

```
[rxnetty-nio-eventloop-3-1] WARN io.reactivex.netty.metrics.BytesInspector - Failed to publish bytes write metrics event. This does *not* stop the pipeline processing.
java.lang.IllegalStateException: void future
    at io.netty.channel.VoidChannelPromise.fail(VoidChannelPromise.java:178)
    at io.netty.channel.VoidChannelPromise.addListener(VoidChannelPromise.java:44)
    at io.netty.channel.VoidChannelPromise.addListener(VoidChannelPromise.java:24)
    at io.reactivex.netty.metrics.BytesInspector.publishBytesWritten(BytesInspector.java:84)
    at io.reactivex.netty.metrics.BytesInspector.write(BytesInspector.java:67)
    at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:633)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:691)
    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:626)
    at io.netty.handler.ssl.SslHandler.finishWrap(SslHandler.java:533)
    at io.netty.handler.ssl.SslHandler.wrap(SslHandler.java:504)
    at io.netty.handler.ssl.SslHandler.flush(SslHandler.java:454)
    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:663)
    at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:644)
    at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117)
    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:663)
    at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:644)
    at io.netty.handler.logging.LoggingHandler.flush(LoggingHandler.java:297)
    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:663)
    at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:644)
    at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115)
    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:663)
    at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:644)
    at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117)
    at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:663)
    at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:644)
    at io.netty.channel.DefaultChannelPipeline.flush(DefaultChannelPipeline.java:897)
    at io.reactivex.netty.protocol.http.server.ServerRequestResponseConverter.channelReadComplete(ServerRequestResponseConverter.java:166)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:337)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelReadComplete(ChannelInboundHandlerAdapter.java:97)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:337)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.codec.ByteToMessageDecoder.channelReadComplete(ByteToMessageDecoder.java:216)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:337)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelReadComplete(ChannelInboundHandlerAdapter.java:97)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:337)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelReadComplete(ChannelInboundHandlerAdapter.java:97)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:337)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:319)
    at io.netty.handler.ssl.SslHandler.channelReadComplete(SslHandler.java:937)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:337)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelReadComplete(ChannelInboundHandlerAdapter.java:97)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:337)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelReadComplete(AbstractChannelHandlerContext.java:319)
    at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:852)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:153)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:744)
```

It is an error while publishing metrics and the error says:

`Failed to publish bytes write metrics event. This does *not* stop the pipeline processing.`

So, it is really a harmless error.

The error is happening because the `write` call is getting an empty `ByteBuf` with a `VoidPromise` that does not allow adding listeners. I will fix it by short-circuiting when the buffer to write is empty.
