### ISSUE TITLE
random timeout exceptions on tests

### ISSUE THREAD

**Issue by gfrison** [ReactiveX/RxNetty#414]
Hello,

I see some timeout errors which occurs randomly. It seems that sometimes the response from the server is not gathered by the client. 

```
io.reactivex.netty.examples.tcp.proxy.ProxyTest > testProxy FAILED
    org.junit.runners.model.TestTimedOutException: test timed out after 60000 milliseconds
        at sun.misc.Unsafe.park(Native Method)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
        at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
        at rx.observables.BlockingObservable.forEach(BlockingObservable.java:128)
        at io.reactivex.netty.examples.tcp.proxy.ProxyClient.main(ProxyClient.java:67)
        at io.reactivex.netty.examples.tcp.proxy.ProxyTest.testProxy(ProxyTest.java:34)
```

```
$ java -version
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

$ uname -a
Linux gf 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

Thank you,

**Comment by NiteshKant** [comment]
Yeah I have seen these sometime happen on travis. I will enable debug logs for tests to track these down.

**Comment by NiteshKant** [comment]
PR #416 adds debug logs, I will update here of my findings for the flakiness.

**Comment by jamesgorman2** [comment]
Hi Nitesh,

did you get any further on this? I have a repo exhibiting this when running tests in a resource constrained environment (eg on a CI server or single core VM; the repo is a fork of [rxnetty-router](https://github.com/Trunkplatform/rxnetty-router) `gradlew test`).

When it will appear:
- Snap CI
- single core Ubuntu VM running on VirtualBox on a MacBook
- commandline/IDEA when a lot of CPU is happening (haven't been able to isolate if IO is also a factor)

We actually have it happening on another service (only in test) but it's currently got too much proprietary in it to show - what we can say is it's not a problem on our deployed services (but we haven't really smashed them yet). Biggest difference between test and deployment is test spins up lots of servers in a short time (sequentially, but still from tens to hundreds in a very small space of time).

I haven't had time to really grok how RxNetty is handling this stuff but I'm happy to get involved in fixing it.

cheers,
James

**Comment by NiteshKant** [comment]
#504 fixes the tests, It was due to the race-condition as mentioned in #505
