### ISSUE TITLE
[0.4.20] NullPointException when closing socket

### ISSUE THREAD

**Issue by probepark** [ReactiveX/RxNetty#602]
Got a NPE..

Caused by: java.lang.NullPointerException
    at io.reactivex.netty.pipeline.ReadTimeoutPipelineConfigurator.disableReadTimeout(ReadTimeoutPipelineConfigurator.java:81)
    at io.reactivex.netty.channel.ObservableConnection._close(ObservableConnection.java:103)
    at io.reactivex.netty.channel.DefaultChannelWriter.close(DefaultChannelWriter.java:191)
    at io.reactivex.netty.channel.DefaultChannelWriter.close(DefaultChannelWriter.java:185)
    at io.reactivex.netty.channel.ObservableConnection.close(ObservableConnection.java:97)
    at io.reactivex.netty.client.PooledConnection.close(PooledConnection.java:72)

please fix this issue..

**Comment by jamesgorman2** [comment]
Hi Probe,

can you please attach a reproduction of this error.

**Comment by probepark** [comment]
@jamesgorman2 
thank you for your time

please, see the below full log

io.reactivex.exceptions.OnErrorNotImplementedException: Attempt to invoke interface method 'io.netty.util.concurrent.EventExecutor io.netty.channel.ChannelHandlerContext.executor()' on a null object reference
    at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.void accept(java.lang.Throwable)(Functions.java:704)
    at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.void accept(java.lang.Object)(Functions.java:701)
    at io.reactivex.internal.observers.LambdaObserver.void onError(java.lang.Throwable)(LambdaObserver.java:77)
    at io.reactivex.internal.observers.LambdaObserver.void onNext(java.lang.Object)(LambdaObserver.java:67)
    at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.void onNext(java.lang.Object)(ObservableFilter.java:52)
    at com.jakewharton.rxrelay2.BehaviorRelay$BehaviorDisposable.boolean test(java.lang.Object)(BehaviorRelay.java:354)
    at com.jakewharton.rxrelay2.BehaviorRelay$BehaviorDisposable.void emitFirst()(BehaviorRelay.java:317)
    at com.jakewharton.rxrelay2.BehaviorRelay.void subscribeActual(io.reactivex.Observer)(BehaviorRelay.java:117)
    at io.reactivex.Observable.void subscribe(io.reactivex.Observer)(Observable.java:10981)
    at io.reactivex.internal.operators.observable.ObservableFilter.void subscribeActual(io.reactivex.Observer)(ObservableFilter.java:30)
    at io.reactivex.Observable.void subscribe(io.reactivex.Observer)(Observable.java:10981)
    at io.reactivex.Observable.io.reactivex.disposables.Disposable subscribe(io.reactivex.functions.Consumer,io.reactivex.functions.Consumer,io.reactivex.functions.Action,io.reactivex.functions.Consumer)(Observable.java:10967)
    at io.reactivex.Observable.io.reactivex.disposables.Disposable subscribe(io.reactivex.functions.Consumer)(Observable.java:10870)
    at hello.session.Session.void close()(Session.java:540)
    at hello.ui.home.HomeCoordinator.void lambda$receiveSession$30$HomeCoordinator(studiox.util.Network$ConnectType)(HomeCoordinator.java:423)
    at hello.ui.home.HomeCoordinator$$Lambda$30.void accept(java.lang.Object)(HomeCoordinator.java)
    at hello.coordinator.RxBinder$1.void onNext(java.lang.Object)(RxBinder.java:54)
    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.void drainNormal()(ObservableObserveOn.java:200)
    at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.void run()(ObservableObserveOn.java:252)
    at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.void run()(HandlerScheduler.java:109)
    at android.os.Handler.null handleCallback(null)(Handler.java:751)
    at android.os.Handler.null dispatchMessage(null)(Handler.java:95)
    at android.os.Looper.null loop(null)(Looper.java:154)
    at android.app.ActivityThread.null main(null)(ActivityThread.java:6646)
    at java.lang.reflect.Method.null invoke(null)(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.null run(null)(ZygoteInit.java:1468)
    at com.android.internal.os.ZygoteInit.null main(null)(ZygoteInit.java:1358)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'io.netty.util.concurrent.EventExecutor io.netty.channel.ChannelHandlerContext.executor()' on a null object reference
    at io.reactivex.netty.pipeline.ReadTimeoutPipelineConfigurator.void disableReadTimeout(io.netty.channel.ChannelPipeline)(ReadTimeoutPipelineConfigurator.java:81)
    at io.reactivex.netty.channel.ObservableConnection.rx.Observable _close(boolean)(ObservableConnection.java:103)
    at io.reactivex.netty.channel.DefaultChannelWriter.rx.Observable close(boolean)(DefaultChannelWriter.java:191)
    at io.reactivex.netty.channel.DefaultChannelWriter.rx.Observable close()(DefaultChannelWriter.java:185)
    at io.reactivex.netty.channel.ObservableConnection.rx.Observable close()(ObservableConnection.java:97)
    at io.reactivex.netty.client.PooledConnection.rx.Observable close()(PooledConnection.java:72)
    at client.RxNettyClient.void close()(RxNettyClient.java:294)
    at client.RxNettyClientConnectionProvider.void disconnectClient()(RxNettyClientConnectionProvider.java:187)
    at client.RxNettyClientConnectionProvider.void sendDisconnectMessage()(RxNettyClientConnectionProvider.java:170)
    at client.RxNettyClientConnectionProvider.void close()(RxNettyClientConnectionProvider.java:138)
    at chat.stomp.StompClient.void disconnect()(StompClient.java:186)
    at chat.ChatApi.void disconnect()(ChatApi.java:448)
    at chat.AbstractChatApi.void close()(AbstractChatApi.java:232)
    at chat.ChatApiV2.void close()(ChatApiV2.java:225)
    at hello.session.Session$$Lambda$68.void accept(java.lang.Object)(Session.java)
    at io.reactivex.internal.observers.LambdaObserver.void onNext(java.lang.Object)(LambdaObserver.java:63)
    ... 23 more
